### ISSUE TITLE
[PE-D] User Guide missing command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#114]
![image.png](https://raw.githubusercontent.com/alvintan01/ped/main/files/954f6065-a0f7-4992-ac75-1cef1a58264d.png)

The command for looking up CS2113T is missing?
Perhaps there should be `show CS2113T`?

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: alvintan01/ped#4

**Comment by ChewyChair** [comment]
`show` command is clearly at the bottom of the screenshot.
