### ISSUE TITLE
[PE-D] Local search not working - returning all results

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#116]
Input: `search -q program`

Output: seems like all modules are being printed, including modules like "ACC1701X Accounting for Decision Makers 4M" which doesn't have program in its name of description.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yeezao/ped#3

**Comment by ChewyChair** [comment]
Invalid command syntax.
