### ISSUE TITLE
Code review for Aditi

### ISSUE THREAD

**Issue by EthanWong2212** [AY2122S1-CS2113T-W12-2/tp#121]
@aditichadha1310

- [ ] Perhaps you could add "//fallthrough" as there is no break
![image](https://user-images.githubusercontent.com/68017484/139537552-d092bd1e-33b3-41ca-8be8-9ee2780475f1.png)

- [ ] Perhaps you can have better naming than "numerator" and "denominator"?
![image](https://user-images.githubusercontent.com/68017484/139537642-5f90a053-0bd0-46cb-a256-3ce6681546c2.png)

**Comment by aditichadha1310** [comment]
Linked to PR #185
