### ISSUE TITLE
[PE-D] Local search does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#131]
![image.png](https://raw.githubusercontent.com/alvintan01/ped/main/files/91558c95-079d-405f-99d3-ac0c23b12b70.png)

Entering `search -q qeh` should return the list of geh modules `locally` but it is currently returning all modules?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: alvintan01/ped#6

**Comment by ChewyChair** [comment]
Duplicate of #116
