### ISSUE TITLE
[PE-D] Invalid grades are still accepted despite error messages

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#141]
![image.png](https://raw.githubusercontent.com/alvintan01/ped/main/files/73bf4ca6-384c-4bf5-a017-8d62982cf7d5.png)

Typing `store SU > CS1231S` will show an error that the grade entered is invalid but it still adds it to the list of modules completed.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: alvintan01/ped#8

**Comment by aditichadha1310** [comment]
Linked to PR #185
