### ISSUE TITLE
[PE-D] removing a module from transcript increases total credits fulfilled

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#151]
![image.png](https://raw.githubusercontent.com/jon-the-melon/ped/main/files/95183527-080c-4712-8a80-e6a52abda5b6.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jon-the-melon/ped#8

**Comment by aditichadha1310** [comment]
Linked to PR #185
