### ISSUE TITLE
[PE-D] Invalid grades can be stored

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#156]
![6.JPG](https://raw.githubusercontent.com/pragyan01/ped/main/files/b1f0e681-d8a6-4d7f-96ba-44a913df6b41.JPG)

Invalid grade of Z+ can be stored for a module

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: pragyan01/ped#6

**Comment by aditichadha1310** [comment]
Linked to PR #185
