### ISSUE TITLE
[PE-D] Every module has a file

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#157]
![image.png](https://raw.githubusercontent.com/alvintan01/ped/main/files/25df0502-2723-4361-aa5c-6c465972707f.png)

Perhaps all the module information can be stored in a `JSON array` in one file? Currently, there are over `8000` files and it is taking a lot of disk resources and it is still not done updating.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: alvintan01/ped#12

**Comment by ChewyChair** [comment]
Intentional design
