### ISSUE TITLE
[PE-D] NullPointerException for local search by faculty

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#173]
input: `search -f soc -q`

![image.png](https://raw.githubusercontent.com/yeezao/ped/main/files/0cf65ede-6e36-463d-8c33-a076aac8483e.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yeezao/ped#15

**Comment by ChewyChair** [comment]
Only reproducible by tampering with files in the local storage.
